### ISSUE TITLE
Join Tabel and model

### ISSUE THREAD

**Issue by mskraddoc** [mliebelt/rails-generator-scaffold_hmt#1]
Excellent.  Looks good.

My guess is you will add functionality for the join table and model next.

In general, it seems to me that your usage will have to
  A) include a model3 at the command line for the join table and model or
  B) Make the join table and model name from model1 and model2   <<< best option
  C) Use a default join model and table name  

Also,  

Model3 should be created in the migration file as well.  No?  

And,  

The association for for model3.rb should look something like:  

class Model3< ActiveRecord::Base
  belongs_to :model1
  belongs_to :model2
end

Thanks so much!!!

Perry

**Comment by mliebelt** [comment]
I will add some issues to the things I think are doable easily (I have no time at the moment to do it). To your issue:
- The names of model1 and model2 are used inside the code of https://github.com/mliebelt/rails-generator-scaffold_hmt/blob/master/scaffold_hmt/scaffold_hmt_generator.rb. See the following lines:
  - The method `jtn` returns the `join_table_name`, and this is a combination of `fnp`(first_name_pluralized) and `snp` (second_name_pluralized).
  - I want to add the option to define the `join_table_name` (and of course `model_name`), so that it can be defined by the user.
- The join_model is created by the line 16: `template 'model.rb', ...` This creates from the file in directory templates the join model with the contents you have described. See the file https://github.com/mliebelt/rails-generator-scaffold_hmt/blob/master/scaffold_hmt/templates/model.rb for the contents.
